# Generated by Django 3.2.3 on 2024-04-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_delete_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='shopping_cart',
        ),
    ]
