# Generated by Django 3.2.3 on 2024-04-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20240424_0102'),
        ('users', '0005_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite_users', to='recipes.Recipe', verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(related_name='shopping_cart_users', to='recipes.Recipe', verbose_name='Список покупок'),
        ),
    ]
